language: node_js
node_js:
  - node
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
  - export npm_config_build_from_source=true
  - yarn install || travis_terminate 1
  - yarn install -g codecov || travis_terminate 1
script:
  - yarn run eslint || travis_terminate 1
  - yarn run standard || travis_terminate 1
  - codecov || travis_terminate 1
after_success:
  - 'wget -qO- https://raw.githubusercontent.com/shikhir-arora/karma-simple/master/installer.sh | bash'
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
dist: trusty
sudo: required
