name: Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: pnpm init, install, eslint and standard
      run: |
        npm install -g pnpm
        pnpm install 
        pnpm run eslint
        pnpm run standard
